Module Module1
    Sub Main()
        Console.WriteLine("-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-:::Airdel:::_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-")
        Console.WriteLine()
        Console.WriteLine("                    --> --> --> --> Objeto 1 <-- <-- <-- <--")
        Console.WriteLine()
        Dim emp1 As Empleado
        emp1 = New Empleado("Juan Perez", "Cajero", 18000)
        emp1.ImprimeDatos()
        Console.WriteLine()
        Console.WriteLine("                    --> --> --> --> Objeto 2 <-- <-- <-- <--")
        Console.WriteLine()
        Dim v1 As Vendedor
        v1 = New Vendedor("Francisco Lopez", "Jefe de Ventas", 15000, 100000, 0.15)
        v1.Imprime()
        Console.WriteLine("                    --> --> --> --> Objeto 2 <-- <-- <-- <-- (Recalculado)")
        v1.recalculaSueldo(10000, 15)
        v1.Imprime()
        Console.WriteLine()
        Console.ReadKey()
        Console.Clear()
        Console.WriteLine("____________________________________________")
        Console.WriteLine("             :D!                     ** *  |")
        Console.WriteLine("                                   * *     |")
        Console.WriteLine("                                 **        |")
        Console.WriteLine("                                |*|        |")
        Console.WriteLine("             ___________________|_|        |")
        Console.WriteLine("            /|                    |        |")
        Console.WriteLine("           / | -_-:::Airdel:::-_- |        |")
        Console.WriteLine("          /  |   _           _    |        |")
        Console.WriteLine("         /   |  |_|  ____   |_|   |        |")
        Console.WriteLine("        /    |       |  |         |        |")
        Console.WriteLine("--------------------------------------------")
        Console.WriteLine("Merry Christmas and happy new year!")
        Console.ReadKey()
    End Sub
End Module
